FROM golang:1.23-alpine AS builder
WORKDIR /app
COPY go.mod go.sum ./
RUN go mod download
COPY . .
RUN go build -o /bin/user-service ./cmd/user-service

FROM alpine:3.20
WORKDIR /app
COPY --from=builder /bin/user-service /app/user-service
EXPOSE 8081
CMD ["/app/user-service"]
