FROM golang:1.23-alpine AS builder
WORKDIR /app
COPY go.mod go.sum ./
RUN go mod download
COPY . .
RUN go build -o /bin/migrator ./cmd/migrator

FROM alpine:3.20
WORKDIR /app
COPY --from=builder /bin/migrator /app/migrator
COPY --from=builder /app/migrations /app/migrations
CMD ["/app/migrator"]
