FROM golang:1.23-alpine AS builder
WORKDIR /app
COPY go.mod go.sum ./
RUN go mod download
COPY . .
RUN go build -o /bin/membership-service ./cmd/membership-service

FROM alpine:3.20
WORKDIR /app
COPY --from=builder /bin/membership-service /app/membership-service
EXPOSE 8082
CMD ["/app/membership-service"]
